services:
  web:
    build: .
    container_name: web
    privileged: true
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proyecto_net
    restart: unless-stopped

networks:
  proyecto_net:
    external: true